/* U7628 */

#define BOARD_PID		"U7628"
#define BOARD_NAME		"U7628"
#define BOARD_DESC		"U7628 4G Wireless Router"
#define BOARD_VENDOR_NAME	"U7628"
#define BOARD_VENDOR_URL	"http://240038901.qq.cn"
#define BOARD_MODEL_URL		"http://240038901.qq.cn"
#define BOARD_BOOT_TIME		20
#define BOARD_FLASH_TIME		120
#define BOARD_GPIO_BTN_RESET	38
#undef BOARD_GPIO_BTN_FN1
#undef BOARD_GPIO_BTN_WPS
#undef  BOARD_GPIO_BTN_ROUTER
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI
#define BOARD_GPIO_LED_SW2G	44
#define BOARD_GPIO_LED_POWER	3
#undef  BOARD_GPIO_LED_LAN
#undef BOARD_GPIO_LED_WAN
#undef  BOARD_GPIO_LED_USB
#undef  BOARD_GPIO_LED_ROUTER
#define BOARD_GPIO_PWR_USB 37
#define BOARD_HAS_5G_11AC	1
#define BOARD_NUM_ANT_5G_TX	0
#define BOARD_NUM_ANT_5G_RX	0
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	1
#define BOARD_HAS_EPHY_L1000	0
#define BOARD_HAS_EPHY_W1000	0
